before_script:
  - rake db:test:load
  - rake db:mnigrate

language: ruby
rvm:
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
